<?xml version="1.0" encoding="utf-8"?><Database Name="IVASAE" EntityNamespace="IVA" ContextNamespace="IVA" Class="DB_IVADataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=localhost\MANUSQL;Initial Catalog=IVASAE;Integrated Security=True" SettingsObjectName="IVASAE.My.MySettings" SettingsPropertyName="IVASAEConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.IVA_TIPO_DOCUMENTO" Member="IVA_TIPO_DOCUMENTO">
    <Type Name="IVA_TIPO_DOCUMENTO">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DS_NOMBRE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SIS_SUFIJO" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="SIS_EXCLU_SUFIJO" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="NM_CHARS_SERIE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CD_DET" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CD_TIPO" Type="System.String" DbType="Char(3)" CanBeNull="true" />
      <Column Name="FLG_COMPRA" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="FLG_VENTA" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="FLG_IMPO_SAE" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="FLG_COMPRA_GRAVADA" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="NM_CHARS_SUFIJO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SIS_EXCLU_SUFIJO_2" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Association Name="IVA_TIPO_DOCUMENTO_IVA_DOC_NO_SAE" Member="IVA_DOC_NO_SAE" ThisKey="ID" OtherKey="ID_TIPO_DOC" Type="IVA_DOC_NO_SAE" />
      <Association Name="IVA_TIPO_DOCUMENTO_IVA_DOC_COMPRA_SAE" Member="IVA_DOC_COMPRA_SAE" ThisKey="ID" OtherKey="ID_TIPO_DOC" Type="IVA_DOC_COMPRA_SAE" />
      <Association Name="IVA_TIPO_DOCUMENTO_IVA_DOC_VENTA_SAE" Member="IVA_DOC_VENTA_SAE" ThisKey="ID" OtherKey="ID_TIPO_DOC" Type="IVA_DOC_VENTA_SAE" />
    </Type>
  </Table>
  <Table Name="dbo.IVA_CLIE_PROV" Member="IVA_CLIE_PROV">
    <Type Name="IVA_CLIE_PROV">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CLAVE" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="DS_NOMBRE" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="DS_DIRECCION" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="DS_NOMBRE_REPRESENTANTE" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="CD_TIPO_LOCALIDAD" Type="System.String" DbType="VarChar(3)" CanBeNull="true" />
      <Column Name="DS_GIRO" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="DS_DEPARTAMENTO" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="DS_NIT" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DS_NUM_REG_FISC" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="DS_DUI" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="FLG_SAE" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="FLG_CLIENTE" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="FLG_PROVEEDOR" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Association Name="IVA_CLIE_PROV_IVA_DOC_NO_SAE" Member="IVA_DOC_NO_SAE" ThisKey="ID" OtherKey="ID_CLIE" Type="IVA_DOC_NO_SAE" />
    </Type>
  </Table>
  <Table Name="dbo.IVA_DETA_COMP_RETE" Member="IVA_DETA_COMP_RETE">
    <Type Name="IVA_DETA_COMP_RETE">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_ENCA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CVE_DOC" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="NM_MONTO_SUJETO" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Column Name="NM_MONTO_RETENIDO" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Association Name="IVA_ENCA_COMP_RETE_IVA_DETA_COMP_RETE" Member="IVA_ENCA_COMP_RETE" ThisKey="ID_ENCA" OtherKey="ID" Type="IVA_ENCA_COMP_RETE" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.V_IVA_DETA_COMP_RETE" Member="V_IVA_DETA_COMP_RETE">
    <Type Name="V_IVA_DETA_COMP_RETE">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_ENCA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CVE_DOC" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="NM_MONTO_SUJETO" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Column Name="NM_MONTO_RETENIDO" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.IVA_DOC_NO_SAE" Member="IVA_DOC_NO_SAE">
    <Type Name="IVA_DOC_NO_SAE">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_CLIE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FE_FECHA" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ID_TIPO_DOC" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CVE_DOC" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="NM_MES" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NM_ANIO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NM_EXENTO" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Column Name="NM_GRAVADO" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Column Name="NM_IVA" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Column Name="NM_RENTA" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Column Name="NM_IVA_RETENIDO" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Column Name="NM_IVA_PERCIVIDO" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Column Name="NM_TOTAL" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Column Name="FLG_COMPRA" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="FLG_VENTA" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Association Name="IVA_CLIE_PROV_IVA_DOC_NO_SAE" Member="IVA_CLIE_PROV" ThisKey="ID_CLIE" OtherKey="ID" Type="IVA_CLIE_PROV" IsForeignKey="true" />
      <Association Name="IVA_TIPO_DOCUMENTO_IVA_DOC_NO_SAE" Member="IVA_TIPO_DOCUMENTO" ThisKey="ID_TIPO_DOC" OtherKey="ID" Type="IVA_TIPO_DOCUMENTO" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.V_IVA_DOC_NO_SAE" Member="V_IVA_DOC_NO_SAE">
    <Type Name="V_IVA_DOC_NO_SAE">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CVE_DOC" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="ID_CLIE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FE_FECHA" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NM_MES" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NM_ANIO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NM_GRAVADO" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Column Name="NM_EXENTO" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Column Name="NM_IVA" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Column Name="NM_RENTA" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Column Name="NM_IVA_RETENIDO" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Column Name="NM_IVA_PERCIVIDO" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Column Name="NM_TOTAL" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Column Name="ID_TIPO_DOC" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FLG_COMPRA" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="FLG_VENTA" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="CLAVE" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="DS_CLIENTE" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="DS_NIT" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DS_NUM_REG_FISC" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="DS_TIPO_DOC" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.V_IVA_CLIE_PROV" Member="V_IVA_CLIE_PROV">
    <Type Name="V_IVA_CLIE_PROV">
      <Column Name="CLAVE" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="DS_NOMBRE" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="FLG_PROVEEDOR" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="FLG_CLIENTE" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.IVA_DOC_COMPRA_SAE" Member="IVA_DOC_COMPRA_SAE">
    <Type Name="IVA_DOC_COMPRA_SAE">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CVE_DOC" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="CVE_PROVEEDOR" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="FE_FECHA" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FE_RECEPCION" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NM_MES" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NM_ANIO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NM_EXENTO" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Column Name="NM_GRAVADO" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Column Name="NM_IVA" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Column Name="NM_RENTA" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Column Name="NM_IVA_RETENIDO" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Column Name="NM_IVA_PERCIVIDO" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Column Name="NM_TOTAL" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Column Name="ID_TIPO_DOC" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="STATUS" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="FLG_BLOQUEADO" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="CVE_DOC_ORIG" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="FLG_NO_INCLUIR" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Association Name="IVA_TIPO_DOCUMENTO_IVA_DOC_COMPRA_SAE" Member="IVA_TIPO_DOCUMENTO" ThisKey="ID_TIPO_DOC" OtherKey="ID" Type="IVA_TIPO_DOCUMENTO" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.IVA_DOC_VENTA_SAE" Member="IVA_DOC_VENTA_SAE">
    <Type Name="IVA_DOC_VENTA_SAE">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CVE_DOC" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="CVE_CLIE" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="FE_FECHA" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FE_ELABORACION" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NM_MES" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NM_ANIO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NM_EXENTO" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Column Name="NM_GRAVADO" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Column Name="NM_IVA" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Column Name="NM_RENTA" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Column Name="NM_IVA_RETENIDO" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Column Name="NM_IVA_PERCIVIDO" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Column Name="NM_TOTAL" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Column Name="ID_TIPO_DOC" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="STATUS" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="FLG_BLOQUEADO" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="CVE_DOC_ORIG" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="FLG_NO_INCLUIR" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Association Name="IVA_TIPO_DOCUMENTO_IVA_DOC_VENTA_SAE" Member="IVA_TIPO_DOCUMENTO" ThisKey="ID_TIPO_DOC" OtherKey="ID" Type="IVA_TIPO_DOCUMENTO" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.V_IVA_DOC_COMPRA_SAE" Member="V_IVA_DOC_COMPRA_SAE">
    <Type Name="V_IVA_DOC_COMPRA_SAE">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CVE_DOC" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="CVE_PROVEEDOR" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="FE_FECHA" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FE_RECEPCION" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NM_MES" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NM_ANIO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NM_EXENTO" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Column Name="NM_GRAVADO" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Column Name="NM_IVA" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Column Name="NM_RENTA" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Column Name="NM_IVA_RETENIDO" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Column Name="NM_IVA_PERCIVIDO" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Column Name="NM_TOTAL" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Column Name="ID_TIPO_DOC" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="STATUS" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="FLG_BLOQUEADO" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="DS_PROVEEDOR" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="DS_NUM_REG_FISC" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="DS_NIT" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DS_TIPO_DOC" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="FLG_NO_INCLUIR" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.V_IVA_DOC_VENTA_SAE" Member="V_IVA_DOC_VENTA_SAE">
    <Type Name="V_IVA_DOC_VENTA_SAE">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CVE_DOC" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="CVE_CLIE" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="FE_FECHA" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FE_ELABORACION" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NM_MES" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NM_ANIO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NM_EXENTO" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Column Name="NM_GRAVADO" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Column Name="NM_IVA" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Column Name="NM_RENTA" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Column Name="NM_IVA_RETENIDO" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Column Name="NM_IVA_PERCIVIDO" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Column Name="NM_TOTAL" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Column Name="ID_TIPO_DOC" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="STATUS" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="FLG_BLOQUEADO" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="DS_CLIENTE" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="DS_NUM_REG_FISC" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="DS_NIT" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DS_TIPO_DOC" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="FLG_NO_INCLUIR" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.IVA_LIBRO_COMPRA" Member="IVA_LIBRO_COMPRA">
    <Type Name="IVA_LIBRO_COMPRA">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CD_CORR" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NM_ANIO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NM_MES" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FECHA" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CVE_DOC" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="DS_NRF" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="CVE_PROVEEDOR" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="DS_PROVEEDOR" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="NM_COMP_EXEN_INT" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Column Name="NM_COMP_GRAV_INT" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Column Name="NM_COMP_EXEN_LOCAL" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Column Name="NM_COMP_GRAV_LOCAL" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Column Name="NM_IVA" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Column Name="NM_TOTAL_COMPRAS" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Column Name="NM_RETENCION" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Column Name="NM_COMPRAS_A_TERCEROS" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Column Name="NM_COMPRAS_NO_CONTRIB" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Column Name="DS_CORR" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.IVA_LIBRO_VENTA_CONTRIBUYENTE" Member="IVA_LIBRO_VENTA_CONTRIBUYENTE">
    <Type Name="IVA_LIBRO_VENTA_CONTRIBUYENTE">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CD_CORR" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NM_ANIO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NM_MES" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FECHA" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CVE_DOC" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="DS_NRF" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="CVE_CLIE" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="DS_CLIENTE" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="NM_NO_SUJETAS" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Column Name="NM_EXENTO" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Column Name="NM_GRAVADO" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Column Name="NM_IVA" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Column Name="NM_PERCEPCION" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Column Name="NM_TOTAL" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Column Name="DS_CORR" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.V_IVA_DETALLE_VENTA" Member="V_IVA_DETALLE_VENTA">
    <Type Name="V_IVA_DETALLE_VENTA">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CVE_DOC" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="DS_CLIENTE" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="FE_FECHA" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DIA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NM_MES" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NM_ANIO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NM_EXENTO" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Column Name="NM_GRAVADO" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Column Name="NM_TOTAL" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Column Name="NM_IVA" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Column Name="NM_EXPORTACION" Type="System.Decimal" DbType="Decimal(30,6)" CanBeNull="true" />
      <Column Name="ID_TIPO_DOC" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CD_TIPO" Type="System.String" DbType="Char(3)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.IVA_CLASE_PRODUCTO" Member="IVA_CLASE_PRODUCTO">
    <Type Name="IVA_CLASE_PRODUCTO">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DS_CLASE_PRODUCTO" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="IVA_CLASE_PRODUCTO_IVA_VENTA_DECLARACION_EXPORTACION" Member="IVA_VENTA_DECLARACION_EXPORTACION" ThisKey="ID" OtherKey="ID_CLASE_PRODUCTO" Type="IVA_VENTA_DECLARACION_EXPORTACION" />
    </Type>
  </Table>
  <Table Name="dbo.IVA_TIPO_DECLARACION" Member="IVA_TIPO_DECLARACION">
    <Type Name="IVA_TIPO_DECLARACION">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DS_DECLARACION" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Association Name="IVA_TIPO_DECLARACION_IVA_VENTA_DECLARACION_EXPORTACION" Member="IVA_VENTA_DECLARACION_EXPORTACION" ThisKey="ID" OtherKey="ID_TIPO_DECLARACION" Type="IVA_VENTA_DECLARACION_EXPORTACION" />
    </Type>
  </Table>
  <Table Name="dbo.V_IVA_VENTA_DECLARACION_EXPORTACION" Member="V_IVA_VENTA_DECLARACION_EXPORTACION">
    <Type Name="V_IVA_VENTA_DECLARACION_EXPORTACION">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ID_DOC_SAE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DS_NM_DECLARACION" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DS_REFERRENCIA" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ID_ADUANA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ID_TIPO_DECLARACION" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FE_DECLARACION" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ID_CLASE_PRODUCTO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DS_DESTINO" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CVE_DOC" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="FE_FECHA" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NM_ANIO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NM_MES" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CD_ESTADO" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="NM_TOTAL" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.IVA_CONTROL_PERIODO" Member="IVA_CONTROL_PERIODO">
    <Type Name="IVA_CONTROL_PERIODO">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MES" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ANIO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CD_ESTADO" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.IVA_ADUANAS" Member="IVA_ADUANAS">
    <Type Name="IVA_ADUANAS">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DS_ADUANA" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="DS_NOMBRE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="IVA_ADUANAS_IVA_VENTA_DECLARACION_EXPORTACION" Member="IVA_VENTA_DECLARACION_EXPORTACION" ThisKey="ID" OtherKey="ID_ADUANA" Type="IVA_VENTA_DECLARACION_EXPORTACION" />
    </Type>
  </Table>
  <Table Name="dbo.V_IVA_RETENCION" Member="V_IVA_RETENCION">
    <Type Name="V_IVA_RETENCION">
      <Column Name="No_DOCTO" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="CVE_CLPV" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="NOMBRE" Type="System.String" DbType="VarChar(120)" CanBeNull="true" />
      <Column Name="RFC" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="NIT" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="CALLE" Type="System.String" DbType="VarChar(80)" CanBeNull="true" />
      <Column Name="FECHA_DOC" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="MES" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ANIO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IMPUESTO" Type="System.Decimal" DbType="Decimal(16,2)" CanBeNull="true" />
      <Column Name="MONTO" Type="System.Decimal" DbType="Decimal(16,2)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.IVA_CONF_COMP_RETE" Member="IVA_CONF_COMP_RETE">
    <Type Name="IVA_CONF_COMP_RETE">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CD_SERIE" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="CD_NUMERO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NM_DOCS_X_COMP" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ID_TIPO_DOC_RETE" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.IVA_ENCA_COMP_RETE" Member="IVA_ENCA_COMP_RETE">
    <Type Name="IVA_ENCA_COMP_RETE">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CVE_PROVEEDOR" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="CD_SERIE" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="CD_NUMERO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FE_FECHA" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NM_MONTO_RETENIDO" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Column Name="NM_EJERCICIO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NM_PERIODO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CD_ESTADO" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="FLG_SUJ_EXCL" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Association Name="IVA_ENCA_COMP_RETE_IVA_DETA_COMP_RETE" Member="IVA_DETA_COMP_RETE" ThisKey="ID" OtherKey="ID_ENCA" Type="IVA_DETA_COMP_RETE" />
    </Type>
  </Table>
  <Table Name="dbo.V_IVA_ENCA_COMP_RETE" Member="V_IVA_ENCA_COMP_RETE">
    <Type Name="V_IVA_ENCA_COMP_RETE">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CVE_PROVEEDOR" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="DS_NOMBRE" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="CD_SERIE" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="CD_NUMERO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FE_FECHA" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CD_ESTADO" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="NM_MONTO_RETENIDO" Type="System.Decimal" DbType="Decimal(38,6)" CanBeNull="true" />
      <Column Name="NM_PERIODO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NM_EJERCICIO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DS_DEPARTAMENTO" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="DS_DIRECCION" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="DS_GIRO" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="DS_NUM_REG_FISC" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="DS_NIT" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NM_MONTO_SUJETO" Type="System.Decimal" DbType="Decimal(38,6)" CanBeNull="true" />
      <Column Name="FLG_SUJ_EXCL" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.IVA_VENTA_DECLARACION_EXPORTACION" Member="IVA_VENTA_DECLARACION_EXPORTACION">
    <Type Name="IVA_VENTA_DECLARACION_EXPORTACION">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_DOC_SAE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DS_NM_DECLARACION" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DS_REFERRENCIA" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ID_ADUANA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ID_TIPO_DECLARACION" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FE_DECLARACION" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ID_CLASE_PRODUCTO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DS_DESTINO" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CD_ESTADO" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="NM_MES" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NM_ANIO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FLG_MANUAL" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Association Name="IVA_ADUANAS_IVA_VENTA_DECLARACION_EXPORTACION" Member="IVA_ADUANAS" ThisKey="ID_ADUANA" OtherKey="ID" Type="IVA_ADUANAS" IsForeignKey="true" />
      <Association Name="IVA_CLASE_PRODUCTO_IVA_VENTA_DECLARACION_EXPORTACION" Member="IVA_CLASE_PRODUCTO" ThisKey="ID_CLASE_PRODUCTO" OtherKey="ID" Type="IVA_CLASE_PRODUCTO" IsForeignKey="true" />
      <Association Name="IVA_TIPO_DECLARACION_IVA_VENTA_DECLARACION_EXPORTACION" Member="IVA_TIPO_DECLARACION" ThisKey="ID_TIPO_DECLARACION" OtherKey="ID" Type="IVA_TIPO_DECLARACION" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.IVA_LIBRO_VENTA_CONSUMIDOR" Member="IVA_LIBRO_VENTA_CONSUMIDOR">
    <Type Name="IVA_LIBRO_VENTA_CONSUMIDOR">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NM_ANIO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NM_MES" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NM_DIA" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="CD_CORR" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NM_DEL_NO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NM_AL_NO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NM_EXPORTACION" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Column Name="CD_SERIE" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="NM_NO_SUJETAS" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Column Name="NM_EXENTAS" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Column Name="NM_GRAVADAS" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Column Name="NM_IVA" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Column Name="NM_TOTAL" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Column Name="DS_DEL_NO" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="DS_AL_NO" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.V_IVA_RPT_RETEN_PERCEP" Member="V_IVA_RPT_RETEN_PERCEP">
    <Type Name="V_IVA_RPT_RETEN_PERCEP">
      <Column Name="No_Doc" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="STATUS" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="CONDICION" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="METODODEPAGO" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="CVE_CLPV" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="NOMBRE" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="RFC" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="NIT" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="DIRECCION" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="PAIS" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="CVE_VEND" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="CVE_PEDI" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="FECHA_DOC" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MES" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Periodo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FECHAELAB" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FECHA_VEN" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CAN_TOT" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="MONTO" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DAI" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="FLETE" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="RETEN_PERCEP" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="IVA" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="IMPORTE" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="FLG_RETEN_PERCEP" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.IVA_DET_930" Member="IVA_DET_930">
    <Type Name="IVA_DET_930">
      <Column Name="NOMBRE" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="NIT" Type="System.String" DbType="VarChar(14)" CanBeNull="true" />
      <Column Name="CALIDAD" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="MODALIDAD" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="COD_DOC" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="NUM_DOC" Type="System.String" DbType="VarChar(16)" CanBeNull="true" />
      <Column Name="MONTO_SUJETO" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="RETENCION" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="PERIODO" Type="System.String" DbType="VarChar(6)" CanBeNull="true" />
      <Column Name="NM_MES" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NM_ANIO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NM_MONTO_SUJETO" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Column Name="NM_RETENCION" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.IVA_DET_987_CLIENTES" Member="IVA_DET_987_CLIENTES">
    <Type Name="IVA_DET_987_CLIENTES">
      <Column Name="MES" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="DOCUMENTO_ID" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="NUM_DOC_ID" Type="System.String" DbType="VarChar(14)" CanBeNull="true" />
      <Column Name="FECHA" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="TIPO_DOC" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="NUM_DOC" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="MONTO_TOTAL" Type="System.String" DbType="VarChar(11)" CanBeNull="true" />
      <Column Name="IVA_TOTAL" Type="System.String" DbType="VarChar(11)" CanBeNull="true" />
      <Column Name="ANIO" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
      <Column Name="NM_MES" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NM_ANIO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NM_MONTO_TOTAL" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Column Name="NM_IVA_TOTAL" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.IVA_DET_987_CLIENTES_M200" Member="IVA_DET_987_CLIENTES_M200">
    <Type Name="IVA_DET_987_CLIENTES_M200">
      <Column Name="FECHA" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="REGISTROS" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="MONTO_TOTAL" Type="System.String" DbType="VarChar(11)" CanBeNull="true" />
      <Column Name="IVA_TOTAL" Type="System.String" DbType="VarChar(11)" CanBeNull="true" />
      <Column Name="ANIO" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
      <Column Name="NM_MES" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NM_ANIO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NM_MONTO_TOTAL" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Column Name="NM_IVA_TOTAL" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.IVA_DET_987_PROVEEDOR_EXCLU_IVA" Member="IVA_DET_987_PROVEEDOR_EXCLU_IVA">
    <Type Name="IVA_DET_987_PROVEEDOR_EXCLU_IVA">
      <Column Name="MES" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="DOCUMENTO_ID" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="NUM_DOC_ID" Type="System.String" DbType="VarChar(14)" CanBeNull="true" />
      <Column Name="FECHA" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="TIPO_DOC" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="NUM_DOC" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="MONTO_TOTAL" Type="System.String" DbType="VarChar(11)" CanBeNull="true" />
      <Column Name="DIRECCION" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="ANIO" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
      <Column Name="NM_MES" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NM_ANIO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NM_MONTO_TOTAL" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.IVA_DET_987_PROVEEDOR_EXTRANJERO" Member="IVA_DET_987_PROVEEDOR_EXTRANJERO">
    <Type Name="IVA_DET_987_PROVEEDOR_EXTRANJERO">
      <Column Name="MES" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
      <Column Name="CONCEPTO" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="DOCUMENTO_ID" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="NUM_DOC_ID" Type="System.String" DbType="VarChar(14)" CanBeNull="true" />
      <Column Name="NOMBRE_PROVEEDOR" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="REPRESENTANTE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="FECHA" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="TIPO_DOC" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="NUM_DOC" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="MONTO_TOTAL" Type="System.String" DbType="VarChar(11)" CanBeNull="true" />
      <Column Name="IVA_TOTAL" Type="System.String" DbType="VarChar(11)" CanBeNull="true" />
      <Column Name="ANIO" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
      <Column Name="NM_MES" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NM_ANIO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NM_MONTO_TOTAL" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Column Name="NM_IVA_TOTAL" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.IVA_DET_987_PROVEEDORES" Member="IVA_DET_987_PROVEEDORES">
    <Type Name="IVA_DET_987_PROVEEDORES">
      <Column Name="MES" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="DOCUMENTO_ID" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="NUM_DOC_ID" Type="System.String" DbType="VarChar(14)" CanBeNull="true" />
      <Column Name="FECHA" Type="System.String" DbType="VarChar(14)" CanBeNull="true" />
      <Column Name="TIPO_DOC" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="NUM_DOC" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="MONTO_TOTAL" Type="System.String" DbType="VarChar(11)" CanBeNull="true" />
      <Column Name="IVA_TOTAL" Type="System.String" DbType="VarChar(11)" CanBeNull="true" />
      <Column Name="ANIO" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
      <Column Name="NM_MES" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NM_ANIO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NM_MONTO_TOTAL" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Column Name="NM_IVA_TOTAL" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.IVA_CONF" Member="IVA_CONF">
    <Type Name="IVA_CONF">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DS_NOMBRE_POLIZA" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ID_DEF_CLASE_PRODUCTO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NM_NIT_EMPRESA" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="NM_NOMBRE_EMPRESA" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="NM_PORC_IVA" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Column Name="NM_REG_FISC" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.PR_IVA_IMPO_CLIE_PROV" Method="PR_IVA_IMPO_CLIE_PROV">
    <Parameter Name="NM_ERROR" Parameter="nM_ERROR" Type="System.Int32" DbType="Int" />
    <Parameter Name="MSJ" Parameter="mSJ" Type="System.String" DbType="VarChar(100)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.PR_IVA_IMPO_COMPRA" Method="PR_IVA_IMPO_COMPRA">
    <Parameter Name="NM_ANIO" Parameter="nM_ANIO" Type="System.Int32" DbType="Int" />
    <Parameter Name="NM_MES" Parameter="nM_MES" Type="System.Int32" DbType="Int" />
    <Parameter Name="MSJ_ERROR" Parameter="mSJ_ERROR" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="NM_ERROR" Parameter="nM_ERROR" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.PR_IVA_IMPO_VENT" Method="PR_IVA_IMPO_VENT">
    <Parameter Name="NM_ANIO" Parameter="nM_ANIO" Type="System.Int32" DbType="Int" />
    <Parameter Name="NM_MES" Parameter="nM_MES" Type="System.Int32" DbType="Int" />
    <Parameter Name="MSJ_ERROR" Parameter="mSJ_ERROR" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="NM_ERROR" Parameter="nM_ERROR" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.PR_IVA_GENE_LIBRO_COMPRA" Method="PR_IVA_GENE_LIBRO_COMPRA">
    <Parameter Name="NM_ANIO" Parameter="nM_ANIO" Type="System.Int32" DbType="Int" />
    <Parameter Name="NM_MES" Parameter="nM_MES" Type="System.Int32" DbType="Int" />
    <Parameter Name="NM_ERROR" Parameter="nM_ERROR" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="MSJ_ERROR" Parameter="mSJ_ERROR" Type="System.String" DbType="VarChar(100)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.PR_IVA_GENE_LIBRO_VENTA" Method="PR_IVA_GENE_LIBRO_VENTA">
    <Parameter Name="NM_ANIO" Parameter="nM_ANIO" Type="System.Int32" DbType="Int" />
    <Parameter Name="NM_MES" Parameter="nM_MES" Type="System.Int32" DbType="Int" />
    <Parameter Name="NM_ERROR" Parameter="nM_ERROR" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="MSJ_ERROR" Parameter="mSJ_ERROR" Type="System.String" DbType="VarChar(100)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.PR_IVA_GENE_LIBRO_VENTA_CONSU" Method="PR_IVA_GENE_LIBRO_VENTA_CONSU">
    <Parameter Name="NM_ANIO" Parameter="nM_ANIO" Type="System.Int32" DbType="Int" />
    <Parameter Name="NM_MES" Parameter="nM_MES" Type="System.Int32" DbType="Int" />
    <Parameter Name="NM_ERROR" Parameter="nM_ERROR" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="MSJ_ERROR" Parameter="mSJ_ERROR" Type="System.String" DbType="VarChar(100)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.PR_IVA_GENE_DET" Method="PR_IVA_GENE_DET">
    <Parameter Name="NM_ANIO" Parameter="nM_ANIO" Type="System.Int32" DbType="Int" />
    <Parameter Name="NM_MES" Parameter="nM_MES" Type="System.Int32" DbType="Int" />
    <Parameter Name="NM_ERROR" Parameter="nM_ERROR" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="MSJ_ERROR" Parameter="mSJ_ERROR" Type="System.String" DbType="VarChar(100)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.PR_IVA_GENE_NM_COMP" Method="PR_IVA_GENE_NM_COMP">
    <Parameter Name="CD_SERIE" Parameter="cD_SERIE" Type="System.String" DbType="VarChar(10)" Direction="InOut" />
    <Parameter Name="CD_NUMERO" Parameter="cD_NUMERO" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.CantidadConLetra" Method="CantidadConLetra" IsComposable="true">
    <Parameter Name="Numero" Parameter="numero" Type="System.Decimal" DbType="Decimal(18,2)" />
    <Return Type="System.String" />
  </Function>
  <Function Name="dbo.PR_IVA_ANUL_COMP_RETE" Method="PR_IVA_ANUL_COMP_RETE">
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <Parameter Name="MSJ_ERROR" Parameter="mSJ_ERROR" Type="System.String" DbType="VarChar(200)" Direction="InOut" />
    <Parameter Name="NM_ERROR" Parameter="nM_ERROR" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.PR_IVA_DATA_RETEN_PERCEP" Method="PR_IVA_DATA_RETEN_PERCEP">
    <Parameter Name="MONTH" Parameter="mONTH" Type="System.Int32" DbType="Int" />
    <Parameter Name="TEMPORADA" Parameter="tEMPORADA" Type="System.Int32" DbType="Int" />
    <ElementType Name="PR_IVA_DATA_RETEN_PERCEPResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="No_Doc" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="STATUS" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="CONDICION" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="METODODEPAGO" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="CVE_CLPV" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="NOMBRE" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="RFC" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="NIT" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="DIRECCION" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="PAIS" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="CVE_VEND" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="CVE_PEDI" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="FECHA_DOC" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MES" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Periodo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FECHAELAB" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FECHA_VEN" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CAN_TOT" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="MONTO" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DAI" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="FLETE" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="RETEN_PERCEP" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="IVA" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="IMPORTE" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="FLG_RETEN_PERCEP" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>